### ISSUE TITLE
question about codex 

### ISSUE THREAD

**Issue by jmjff** [joyhsu0504/NS3D#10]
Hi, thanks for your wonderful work! I have some questions about how to use the codex to produce programs with prompts. In your code, codex_out.p is provided to perform instance-level 3D visual grounding, but I wonder how to get that result, i.e codex_out.p. Can you provide the code about how to parse the language into programs?
Thank you very much for your kind consideration, and I look forward to your early reply.

Best Regards!

**Comment by joyhsu0504** [comment]
Thanks for reaching out! See this [issue](https://github.com/joyhsu0504/NS3D/issues/3); we prompted Codex with the following [prompts](https://drive.google.com/file/d/1_zah7dpRdSVx6IrJ1CmnBQfxiPsts1pQ/view). As Codex is deprecated, GPT 3.5 or 4 should produce similar results.
