### ISSUE TITLE
How to use Codex to generate symbolic programs?

### ISSUE THREAD

**Issue by anitacen** [joyhsu0504/NS3D#3]
I am currently looking to run some tests on a new text input, and I was wondering if you could provide some insight into how you utilized Codex. Thanks a lot.

**Comment by joyhsu0504** [comment]
Thanks for reaching out! We prompted Codex with the following [prompts](https://drive.google.com/file/d/1_zah7dpRdSVx6IrJ1CmnBQfxiPsts1pQ/view?usp=sharing).
