### ISSUE TITLE
Why KeyError: 'scene0505_02' occurs during Evaluation and Training

### ISSUE THREAD

**Issue by zeyu659** [joyhsu0504/NS3D#4]
In the Evaluation process, the scannet data was first processed and ‘kept_all_points_with_global_scan_alignment.pkl‘ was generated, then ‘sr3d_train.csv’ and ’trained_ns3d.pth’ were downloaded. During the execution of 'jac-run', it always appeared 'KeyError: 'scene0***_**'', and the 'scene0_' file is still different every time. This problem also occurs in the Training process. What is the reason for this? Thank you for your answer!

**Comment by joyhsu0504** [comment]
Please send your full stack trace and where the error occurs, as I have not encountered this issue. Thanks!

**Comment by joyhsu0504** [comment]
Closing as inactive.
