### ISSUE TITLE
feed_dict seems to be a list, not a dict

### ISSUE THREAD

**Issue by ZoomPkk** [joyhsu0504/NS3D#6]
Hi @joyhsu0504 
when i try to run trainval.py, it seems like feed_dict is constructed as a list of dicts, so strings like 'utterance' can't be its indices,
do you have any idea to solve it?
Thank you for your attention!

Traceback (most recent call last):
  File "ns3d/trainval.py", line 523, in <module>
    main()
  File "ns3d/trainval.py", line 246, in main
    train_epoch(epoch, trainer, train_dataloader, meters, all_scans_in_dict)
  File "ns3d/trainval.py", line 292, in train_epoch
    feed_dict['input_str'] = feed_dict['utterance']
TypeError: list indices must be integers or slices, not str

**Comment by joyhsu0504** [comment]
Hi, feed_dict should be a dict, with utterance set as the following: https://github.com/joyhsu0504/NS3D/blob/main/datasets/referit3d/listening_dataset.py#L255.

**Comment by joyhsu0504** [comment]
Closing as inactive.

**Comment by liujm2001** [comment]
I got the same problem and fixed it by setting args.gpu_parallel = False. When using paralleled gpus, feed_dict will become a list with the same length of number of gpus, instead of a dict.
