### ISSUE TITLE
Pretrained weights of pointnet++ classification net

### ISSUE THREAD

**Issue by tony10101105** [joyhsu0504/NS3D#7]
Hi,

Thanks for the great work!
For the pretrained weights of pointenet++ classification model you provided in the training scripts, seems you wrap the loading of entire model (instead of loading pretrained weights of each component of your framework separately). So I am not able to get the weights of only pointnet++ and load it solely, which I want to use in my own project.
Do you think there's any way to solve this issue?

**Comment by joyhsu0504** [comment]
I'm not quite sure I understand your question -- if your goal is to retrieve the PointNet++ weights, you can load the full model, extract the weights from the PointNet++ component you'd like (such as in https://github.com/joyhsu0504/NS3D/blob/main/models/scene_graph/scene_graph_pointnet.py#L38), and save just those weights for easier access.

**Comment by tony10101105** [comment]
Oh, got it. Thanks for your reply!
