### ISSUE TITLE
A question about grammar parsers

### ISSUE THREAD

**Issue by Terry-Joy** [joyhsu0504/NS3D#8]
I'm very sorry to bother you, but you mentioned in your paper that your grammar parser uses the Codex code framework. I don't seem to see this part in your code, does it refer to the code in the semantics folder

**Comment by joyhsu0504** [comment]
Thanks for reaching out! See this [issue](https://github.com/joyhsu0504/NS3D/issues/3); we prompted Codex with the following [prompts](https://drive.google.com/file/d/1_zah7dpRdSVx6IrJ1CmnBQfxiPsts1pQ/view).
