### ISSUE TITLE
Slow evaluation time

### ISSUE THREAD

**Issue by tony10101105** [joyhsu0504/NS3D#9]
Hi,

I am trying to reproduce your results. I found that the validation time per batch (~3s on a V100) is much slower than the training time per batch. Is this an expected running time? Since the default total epoch is 5000, it will take too long to complete a run. 
<img width="554" alt="螢幕快照 2023-12-30 下午12 17 11" src="https://github.com/joyhsu0504/NS3D/assets/43724128/99ef0a4b-d1e9-4e16-b107-0ded033348d6">

In addition, could you provide the sr3d dataset split used in your paper (0.5%, 1.5%, 2.5%, 5%, 10%)? Thanks!

**Comment by joyhsu0504** [comment]
Your run should converge well within 100 epochs; I believe 50 epochs is enough. In addition, you may set the `--validation-interval` flag to decrease the frequency of validation. 

The SR3D splits used can be found [here](https://drive.google.com/drive/folders/1R5VHMTAmeuQs0TtHflSahs3EHkQHfEDs). See `sr3d_train_0d5p.csv` through `sr3d_train_10p.csv`. Thanks!
